server:
  port: 8070


spring:
  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: true
              lower-case-service-id: true


management:
  endpoint:
    gateway:
      access: unrestricted

info:
  app:
    name: "gateway-server"
    description: "edge server to my ecommerce microservice network"

resilience4j.circuitbreaker:
  configs:
    ordersCircuitBreaker:
      sliding-window-size: 10
      permitted-number-of-calls-in-half-open-state: 5
      failure-rate-threshold: 50
      wait-duration-in-open-state:
        seconds: 60
