server:
  port: 8070


spring:
  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: true
              lower-case-service-id: true


management:
  endpoint:
    gateway:
      access: unrestricted

info:
  app:
    name: "gateway-server"
    description: "edge server to my ecommerce microservice network"
