


management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readinessstate:
      enabled: true
    livenessstate:
      enabled: true
  endpoint:
    shutdown:
      access: unrestricted
    health:
      probes:
        enabled: true
  info:
    env:
      enabled: true
  metrics:
    tags:
      application: ${spring.application.name}




logging:
  level:
    root: INFO

    com.shoppy: DEBUG

    io.github.resilience4j: DEBUG

    org.springframework.cloud.gateway: DEBUG

    org.springframework.cloud.openfeign: DEBUG
  pattern:
    level: "%5p[${spring.application.name}, %X{trace_id}, %X{span_id}]"
