spring:
  datasource:
    url: "jdbc:postgresql://localhost:5433/product_catalog_db"
    username: postgres
    password: bhanu0218
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true



server:
  port: 8080

info:
  app:
    name: "items"
    description: "items catalog service for our ecommerce application"

resilience4j:
  retry:
    instances:
      getItemsId:
        wait-duration: 100ms
        max-attempts: 15
        exponential-backoff-multiplier: 2
        enable-exponential-backoff: true
        exponential-max-wait-duration: 1000ms
        ignore-exceptions:
          - java.lang.NullPointerException
  ratelimiter:
    instances:
      getItemById:
        limit-for-period: 1
        limit-refresh-period: 5s
        timeout-duration: 1s

logging:
  level:
    io.github.resilience4j: DEBUG
