spring:
  datasource:
    url: "jdbc:postgresql://localhost:5433/order_service"
    username: postgres
    password: bhanu0218
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  cloud:
    openfeign:
      circuitbreaker:
        enabled: true

server:
  port: 8085

info:
  app:
    name: "orders"
    description: "orders service of our ecommerce application"
    
resilience4j.circuitbreaker:
  configs:
    default:
      sliding-window-size: 10
      permitted-number-of-calls-in-half-open-state: 5
      failure-rate-threshold: 50
      wait-duration-in-open-state:
        seconds: 60
