spring:
  datasource:
    url: "jdbc:postgresql://localhost:5433/order_service"
    username: postgres
    password: bhanu0218
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  cloud:
    openfeign:
      circuitbreaker:
        enabled: false

server:
  port: 8085

info:
  app:
    name: "orders"
    description: "orders service of our ecommerce application"
    


resilience4j:
  circuitbreaker:
    instances:
      ItemServiceCB:
        register-health-indicator: true
        sliding-window-type: count_based
        sliding-window-size: 20
        minimum-number-of-calls: 10
        failure-rate-threshold: 50
        automatic-transition-from-open-to-half-open-enabled: true
        permitted-number-of-calls-in-half-open-state: 5
        wait-duration-in-open-state:
          seconds: 30
        slow-call-rate-threshold: 50
        slow-call-duration-threshold: 2s
  retry:
    instances:
      getItemsId:
        wait-duration: 100ms
        max-attempts: 3
        exponential-backoff-multiplier: 2
        enable-exponential-backoff: true
        exponential-max-wait-duration: 1000ms
        ignore-exceptions:
          - java.lang.NullPointerException
          - io.github.resilience4j.ratelimiter.RequestNotPermitted
        retry-exceptions:
          - feign.RetryableException
          - java.net.SocketTimeoutException
          - java.net.ConnectException
